### ISSUE TITLE
`chunk.hasRuntime is not a function` with Angular & Babel

### ISSUE THREAD

**Issue by terotil** [gajus/prepack-webpack-plugin#18]
There's prolly something really obvious here that I'm missing. Plugin seems to refuse to work with my stack, which is a fork of http://juhamust.github.io/silverplate

Steps to reproduce
- `git clone https://github.com/juhamust/silverplate.git`
- `npm install`
- `npm install prepack-webpack-plugin --save-dev`
- Do the minimal setup according to instructions

After this

```
$ git diff
diff --git a/package.json b/package.json
index 140f670..e6aaff4 100644
--- a/package.json
+++ b/package.json
@@ -51,6 +51,7 @@
     "normalize.css": "^3.0.3",
     "postcss-loader": "^0.8.0",
     "precss": "^1.4.0",
+    "prepack-webpack-plugin": "^1.1.0",
     "raw-loader": "^0.5.1",
     "resolve-url": "^0.2.1",
     "resolve-url-loader": "^1.4.3",
diff --git a/webpack.config.js b/webpack.config.js
index 3fa42f4..fbf1b74 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -5,6 +5,7 @@ var CommonsChunkPlugin = require('webpack/lib/optimize/CommonsChunkPlugin');
 var autoprefixer = require('autoprefixer');
 var precss = require('precss');
 var packageInfo = require('./package.json');
+var PrepackWebpackPlugin = require('prepack-webpack-plugin').default;
 
 module.exports = {
   context: __dirname,
@@ -30,6 +31,8 @@ module.exports = {
   },
   noParse: [],
   plugins: [
+    new PrepackWebpackPlugin({
+    }),
     new ExtractTextPlugin('app.css', { allChunks: true }),
     new HtmlWebpackPlugin({
       version: packageInfo.version,
```

Then fire it up

```
$ npm start
[...]
/home/tero/src/silverplate/node_modules/prepack-webpack-plugin/dist/PrepackPlugin.js:27
  return chunk.hasRuntime() && chunk.isInitial();
               ^

TypeError: chunk.hasRuntime is not a function
    at isEntryChunk (/home/tero/src/silverplate/node_modules/prepack-webpack-plugin/src/PrepackPlugin.js:23:16)
```

There seems to be abundance of causes for `chunk.hasRuntime is not a function` and I couldn't find out how to make it work.

**Comment by gajus** [comment]
Does it work with prepack alone?

**Comment by aakilfernandes** [comment]
Same issue. My output is here: https://gist.github.com/aakilfernandes/0a578bc820598009e36b440292344dcb

**Comment by xfcdxg** [comment]
![image](https://cloud.githubusercontent.com/assets/16435465/25831890/ae04fd7a-3499-11e7-8bf0-467530f0db00.png)

**Comment by matteoantoci** [comment]
I have the same problem too, I'm using a bunch of plugins, uglify, occurence order, common chunks, dll reference... I you want I can share with you some more details.

**Comment by dhatawesomedude** [comment]
same here. I have this issue with the same output.

**Comment by gajus** [comment]
If someone wants to take a dab into this one, I am happy to provide rapid response.

However, as it currently works across all the project that I am using it with, I am not able to dedicate time to investigate this specific use case.

**Comment by sesm** [comment]
@gajus Does any of your projects use webpack 1.x ?
Looking at issues like https://github.com/webpack/webpack/issues/2764 my guess it that ``chunk.hasRuntime`` was added in webpack 2.
Can we do something like this?
```
const isEntryChunk = chunk => {
  if(typeof chunk.hasRuntime === 'function') {
    return chunk.hasRuntime() && chunk.isInitial();
  } else {
    return chunk.entry;
  }
};
```

**Comment by sesm** [comment]
I've tried the fix above with my current project (which uses webpack 1.12.9) and I get the following error:
```
This operation is not yet supported on abstract value Date.now() 
__IntrospectionError
    at eval:27:13
    at baseRest (unknown)
    at eval:27:18
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:12:19
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:17:29
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:11:25
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:8:19
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:8:20
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:1:18
    at call (native)
    at __webpack_require__ (unknown)
    at fn (main.js:76:20)
    at eval:1:1
    at call (native)
    at __webpack_require__ (unknown)
```
Since the build progressed further, does it mean that the fix was successfull? XD

**Comment by gajus** [comment]
> @gajus Does any of your projects use webpack 1.x ?

No. For clarity, this plugin is intended to be used only with webpack v2.

**Comment by sesm** [comment]
@gajus Ok, then some documentation disclaimer and/or error message in console would be nice

@terotil Silverplate uses webpack 1 (looking at https://github.com/juhamust/silverplate/blob/master/package.json), does your project also use webpack 1?

@aakilfernandes @xfcdxg @matteoantoci @dhatawesomedude Guys, are you using webpack 1 too?

**Comment by terotil** [comment]
I'm on webpack 1. Need to check if the upgrade is a possibility. Tanks a lot @gajus and @sesm !

**Comment by dhatawesomedude** [comment]
I was on webpack 1. I have updated to webpack 2 so I no longer have this error. I now have #17
