### ISSUE TITLE
This operation not yet supported on an abstract value

### ISSUE THREAD

**Issue by ccorcos** [gajus/prepack-webpack-plugin#20]
Gave this a shot on a pretty big codebase as an experiment and I got this error:

```
This operation is not yet supported on abstract value
__IntrospectionError
    at app.js:19887:56
    at call (native)
    at __webpack_require__ (app.js:20:12)
    at app.js:127578:29
    at call (native)
    at __webpack_require__ (app.js:20:12)
    at app.js:17934:18
    at call (native)
    at __webpack_require__ (app.js:20:12)
    at app.js:137943:16
    at call (native)
    at __webpack_require__ (app.js:20:12)
    at app.js:66:18
    at app.js:1:10

/Users/chet/Code/notion-next/node_modules/prepack/src/prepack-standalone.js:24
  let self = new Error("An error occurred while prepacking. See the error logs.");
             ^
Error: An error occurred while prepacking. See the error logs.
    at new InitializationError (/Users/chet/Code/notion-next/node_modules/prepack/src/prepack-standalone.js:24:14)
    at prepack (/Users/chet/Code/notion-next/node_modules/prepack/src/prepack-standalone.js:39:11)
    at Compilation.compilation.plugin (/Users/chet/Code/notion-next/node_modules/prepack-webpack-plugin/src/PrepackPlugin.js:58:35)
    at Compilation.applyPluginsAsyncSeries (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:626:10)
    at Compilation.applyPluginsAsyncSeries (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:622:9)
    at Compilation.applyPluginsAsyncSeries (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:570:8)
    at /Users/chet/Code/notion-next/node_modules/webpack/lib/Compiler.js:474:16
```

Any ideas where I might find those logs?

**Comment by wx-chevalier** [comment]
i also run into those bugs, when i use commonChunksPlugin to separate vendor.js：
```
  //自动分割Vendor代码
  new webpack.optimize.CommonsChunkPlugin({
    name: "vendors",
    filename: "vendors.bundle.js",
    minChunks: 2
  }),
```
but if i empty the vendors.js, no bugs happen

**Comment by syryls** [comment]
I got the same error with webpack and style adding problem too

``` 
    at createStyleElement (public/js/bundle.js:1265:44)
    at addStyle (public/js/bundle.js:1311:18)
    at addStylesToDom (public/js/bundle.js:1209:16)`

**Comment by freshstrangemusic** [comment]
Take a look at https://github.com/facebook/prepack/issues/521

**Comment by zackify** [comment]
Yeah, I'm getting this too, haven't narrowed it down yet, but I have commons chunk and extract text plugin which get referenced in the error message.
