### ISSUE TITLE
Compatibility with old webpack

### ISSUE THREAD

**Issue by danomatic** [gajus/prepack-webpack-plugin#21]
This doesn't work for older versions of webpack.  For compatibility, can you consider changing:

```
const isEntryChunk = (chunk: Object) => {
  return chunk.hasRuntime() && chunk.isInitial();
};
```

to:

```
const isEntryChunk = (chunk: Object) => {
  return ((chunk.hasRuntime && chunk.hasRuntime()) || chunk.entry) && ((chunk.isInitial && chunk.isInitial()) || chunk.initial);
};
```

**Comment by gajus** [comment]
Have you confirmed that it makes it work with webpack v1?

**Comment by danomatic** [comment]
It seemed to.  I was running against a large React codebase. It got past the error related to these lines in your plug-in, and then crashed with one of the standard prepack errors. I haven't tested against anything else yet.

**Comment by danomatic** [comment]
The output I got after my fix was:

```
This operation is not yet supported on abstract value      
__IntrospectionError
    at bundle-392ece6018c28ff07e50.js:29674:71
    at call (native)
    at __webpack_require__ (bundle-392ece6018c28ff07e50.js:20:12)
    at bundle-392ece6018c28ff07e50.js:4344:17
    at call (native)
    at __webpack_require__ (bundle-392ece6018c28ff07e50.js:20:12)
    at bundle-392ece6018c28ff07e50.js:169446:22
    at call (native)
```
Which I belive means my code can't be prepacked.
