### ISSUE TITLE
prepack is not a function

### ISSUE THREAD

**Issue by ccorcos** [gajus/prepack-webpack-plugin#34]
```
/Users/chet/Code/notion-next/node_modules/prepack-webpack-plugin/src/PrepackPlugin.js:58
            const prepackedCode = prepack(code, {
                                  ^
TypeError: (0 , _prepack.prepack) is not a function
    at Compilation.compilation.plugin (/Users/chet/Code/notion-next/node_modules/prepack-webpack-plugin/src/PrepackPlugin.js:58:35)
    at Compilation.applyPluginsAsyncSeries (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/chet/Code/notion-next/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at next (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/Users/chet/Code/notion-next/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:662:9)
    at next (/Users/chet/Code/notion-next/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/chet/Code/notion-next/node_modules/extract-text-webpack-plugin/dist/index.js:244:13
    at /Users/chet/Code/notion-next/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/chet/Code/notion-next/node_modules/async/dist/async.js:1050:13)
    at /Users/chet/Code/notion-next/node_modules/async/dist/async.js:958:16
    at /Users/chet/Code/notion-next/node_modules/extract-text-webpack-plugin/dist/index.js:227:15
    at /Users/chet/Code/notion-next/node_modules/async/dist/async.js:473:16
```

**Comment by ccorcos** [comment]
It appears prepack 0.2.30 doesn't have a prepack export...

**Comment by g-harel** [comment]
Having the same issue. Also, if I place put the uglifyjs plugin before it, the build silently fails with no output, even with `--verbose`.

**Comment by g-harel** [comment]
I solved the problem in my case by adding a strict prepack version to `package.json`

```json
    "prepack": "0.2.27",
    "prepack-webpack-plugin": "^1.1.0",
```

version `0.2.27` was the most recent one that still works

**Comment by gajus** [comment]
It is open-source package. I don't have resources to inspect this issue at the moment. However, PR would be welcome.

**Comment by trueadm** [comment]
@mxstbr I believe your change in https://github.com/mxstbr/prepack-webpack-plugin/commit/23de2f988ed83dd8d36173d5260928914b99ad5a is the right fix. I'm not sure why this change happened other than we changed how we compile the Prepack source (it used to use the ES2015 transform but we dropped that, potentially causing this issue).

**Comment by mxstbr** [comment]
@trueadm that actually didn't work—I think this does though: #36 

It seems like the runtime API was changed entirely from `prepack.prepack` to `prepack.prepackFile(Sync)` and `prepack.prepackSources(sources)` in some version after `v2.27`.

**Comment by 7iomka** [comment]
Please, update package on NPM!

**Comment by lkmadushan** [comment]
@7iomka still getting same error!

**Comment by leonidkuznetsov18** [comment]
still getting same error!
```
"prepack": "^0.2.34",
"prepack-webpack-plugin": "^1.1.0",
"webpack": "^4.6.0",
"webpack-cli": "^2.0.15",
```
```
node - v9.11.1
npm - 6.0.1
```
