### ISSUE TITLE
Warn: PP0023: Program may terminate with exception: require is not defined

### ISSUE THREAD

**Issue by micheleriso** [gajus/prepack-webpack-plugin#47]
Hi, I'm trying to include this plugin in my webpack configuration but it is throwing this error:

`Warn: PP0023: Program may terminate with exception: require is not defined
  ReferenceError
    at server.js:22302:18
    at __webpack_require__ (server.js:20:12)
    at server.js:22293:1
    at __webpack_require__ (server.js:20:12)
    at server.js:84:18
    at server.js:1:10 at 22302:17 to 22302:24
Error`

I'm using babel and I've removed Uglify to avoid any incompatibility
Thanks

**Comment by stackdumper** [comment]
Please provide the following information:
1. Webpack configuration
2. Webpack version
3. Node.js version

**Comment by gajus** [comment]
> Please provide the following information:

@stackdumper Could you PR contributing guidelines?

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Just a polite message asking to provide the necessary environment variables and command line to get those variables.

**Comment by stackdumper** [comment]
> Could you PR contributing guidelines?

@gajus Would the issue templates be suitable for this?

**Comment by gajus** [comment]
> @gajus Would the issue templates be suitable for this?

Sorry, thats exactly what I have meant – issue template.

Here are several examples:

* https://github.com/stevemao/github-issue-templates
* https://github.com/devspace/awesome-github-templates
