### ISSUE TITLE
webpack unhandledRejection error

### ISSUE THREAD

**Issue by shenburak** [gajus/prepack-webpack-plugin#51]
## Actual Behavior
unhandledRejection TypeError: Cannot read property 'compilation' of undefined

## Specifications

  - Node.js version: 9.10.1
  - Plugin version: 1.1.1
  - Webpack version: 4.17.1

**Comment by stackdumper** [comment]
Are you totally sure that you are using `webpack` version `>= 4`? Please try removing `node_modules` directory and running `npm install` again.

```bash
rm -rf ./node_modules && npm install
```

**Comment by igoldny** [comment]
i have the same issue with next.js v6.1.1 which use webpack 4

```
(node:10663) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compilation' of undefined
    at PrepackPlugin.apply (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/prepack-webpack-plugin/dist/PrepackPlugin.js:33:20)
    at Compiler.apply (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/webpack/lib/webpack.js:33:19)
    at options.map.options (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/webpack/lib/webpack.js:23:55)
    at Array.map (<anonymous>)
    at webpack (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/webpack/lib/webpack.js:23:40)
    at HotReloader._callee3$ (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/next/dist/server/hot-reloader.js:248:49)
    at tryCatch (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/igoldny/Documents/fx-ui/packages/fx-coinz/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
(node:10663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
